secure xml
Bedework/bw-webdav pull request #1
Opened 2018-11-21 22:57 UTC by viqueen

I found out that this library is open to some xml vulnerabilities (xxe / ssrf)
This pull request ensures both the MethodBase and PostRequestPars types are relying on xml secure processing of requests

2018-11-27 22:32 UTC, douglm requested changes
Great change - thank you. Could you drop the change to gitignore and reindent to 2 spaces?

I'm about to roll out a new release and I'd like this in there.

2018-11-28 12:24 UTC, viqueen commented on mvnvm.properties
> +mvn_version=3.5.4
we use the following to manage maven versions across developers http://mvnvm.org/
thought it might be useful here

2018-11-28 15:28 UTC, douglm commented on mvnvm.properties
> +mvn_version=3.5.4
Thanks - I'll take a look

2018-11-28 15:30 UTC, douglm approved these changes
This all looks good - thanks

2018-11-28 15:31 UTC, merged